services:
  app:
    build: ./app
    ports:
      - 127.0.0.1:3000:3000
    environment:
      DATABASE_URL: $APP_DATABASE_URL
      MONGODB_URI: $PAYLOAD_CMS_DATABASE_URL
    volumes:
      - ./app:/app
      - app_node_modules:/app/node_modules
    depends_on:
      mysql:
        condition: service_healthy
  
  storybook:
    image: node:20
    working_dir: /app
    command: bash -c "yarn && yarn storybook"
    ports:
      - 127.0.0.1:6006:6006
    environment:
      DATABASE_URL: $APP_DATABASE_URL
    volumes:
      - "./app:/app"
      - app_node_modules:/app/node_modules

  mysql:
    image: mysql:8
    environment:
      MYSQL_TCP_PORT: $MYSQL_TCP_PORT
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    volumes:
      - mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 30s
      timeout: 5s
      retries: 6
      start_period: 30s
  
  mongo:
    image: mongo
    command: "mongod --port ${MONGO_PORT}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_ROOT_PASSWORD
    volumes:
      - mongo:/data/db

  setup:
    build: ./setup
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  app_node_modules:
  cms_node_modules:
  mysql:
  mongo: